export default [
    {
        name: "Harry Potter and the Sorcerer's Stone",
        id: 1,
        price: 100,
        quantity: 10,
        image: "https://images-na.ssl-images-amazon.com/images/I/51HSkTKlauL._SX346_BO1,204,203,200_.jpg",
        author: "J.K. Rolling",
        detail: "Harry Potter has no idea how famous he is. That's because he's being raised by his miserable aunt and uncle who are terrified Harry will learn that he's really a wizard, just as his parents were. But everything changes when Harry is summoned to attend an infamous school for wizards, and he begins to discover some clues about his illustrious birthright. From the surprising way he is greeted by a lovable giant, to the unique curriculum and colorful faculty at his unusual school, Harry finds himself drawn deep inside a mystical world he never knew existed and closer to his own noble destiny.",
        rating: 4,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Chamber of secrets",
        id: 2,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/51jNORv6nQL._SX340_BO1,204,203,200_.jpg",
        author: "J.K. Rolling",
        detail: "The Dursleys were so mean that hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he's packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.",
        rating: 3,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter And The Prisoner Of Azkaban",
        id: 3,
        price: 100,
        quantity: 5,
        image: "https://images-na.ssl-images-amazon.com/images/I/81lAPl9Fl0L.jpg",
        author: "J.K. Rolling",
        detail: "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.",
        rating: 2,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Chamber of Secrets",
        id: 4,
        price: 100,
        quantity: 50,
        image: "http://4.bp.blogspot.com/-A5J80aW_RTo/VVlTm4t_1NI/AAAAAAAABs4/RCmde59m5HQ/s400/kkhp2.jpg",
        author: "J.K. Rolling",
        detail:"The Dursleys were so mean and hideous that summer that all Harry Potter wanted was to get back to the Hogwarts School for Witchcraft and Wizardry. But just as he’s packing his bags, Harry receives a warning from a strange, impish creature named Dobby who says that if Harry Potter returns to Hogwarts, disaster will strike.",
        rating: 5,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Goblet of Fire",
        id: 5,
        price: 100,
        quantity: 5,
        image: "https://prodimage.images-bn.com/pimages/9780439139601_p0_v1_s550x406.jpg",
        author: "J.K. Rolling",
        detail: "Harry Potter is midway through his training as a wizard and his coming of age. Harry wants to get away from the pernicious Dursleys and go to the International Quidditch Cup. He wants to find out about the mysterious event that's supposed to take place at Hogwarts this year, an event involving two other rival schools of magic, and a competition that hasn't happened for a hundred years. He wants to be a normal, fourteen-year-old wizard. But unfortunately for Harry Potter, he's not normal - even by wizarding standards. And in his case, different can be deadly.",
        rating: 5,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Order of the Phoenix ",
        id: 6,
        price: 100,
        quantity: 15,
        image: "https://prodimage.images-bn.com/pimages/9780439358064_p0_v3_s550x406.jpg",
        author: "J.K. Rolling",
        detail: "Harry Potter and the Order of the Phoenix is a fantasy novel written by British author J. K. Rowling and the fifth novel in the Harry Potter series. It follows Harry Potter's struggles through his fifth year at Hogwarts School of Witchcraft and Wizardry, including the surreptitious return of the antagonist Lord Voldemort, O.W.L. exams, and an obstructive Ministry of Magic. The novel was published on 21 June 2003 by Bloomsbury in the United Kingdom, Scholastic in the United States, and Raincoast in Canada. It sold five million copies in the first 24 hours of publication.It is the longest book of the series.",
        rating: 4,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Half-Blood Prince",
        id: 7,
        price: 100,
        quantity: 15,
        image: "https://images-na.ssl-images-amazon.com/images/I/51uO1pQc5oL._SX329_BO1,204,203,200_.jpg",
        author: "J.K. Rolling",
        detail: "Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J.K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter's sixth year at Hogwarts, the novel explores the past of Harry's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.",
        rating: 3,
        type: "novel",
        promotion: true
    },
    {
        name: "Harry Potter and the Deathly Hallows",
        id: 8,
        price: 100,
        quantity: 15,
        image: "https://images-na.ssl-images-amazon.com/images/I/51A6k0YGQOL._SX331_BO1,204,203,200_.jpg",
        author: "J.K. Rolling",
        detail: "Harry Potter and the Deathly Hallows is a fantasy novel written by British author J. K. Rowling and the seventh and final novel of the Harry Potter series. It was released on 21 July 2007 in the United Kingdom by Bloomsbury Publishing, in the United States by Scholastic, and in Canada by Raincoast Books. The novel chronicles the events directly following Harry Potter and the Half-Blood Prince (2005) and the final confrontation between the wizards Harry Potter and Lord Voldemort.",
        rating: 4,
        type: "novel",
        promotion: true
    },
    {
        name: "Mockingjay 1",
        id: 9,
        price: 100,
        quantity: 15,
        image: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Mockingjay.JPG/220px-Mockingjay.JPG",
        author: "Suzanne Collins",
        detail: "Mockingjay is a 2010 science fiction novel by American author Suzanne Collins. It is the last installment of The Hunger Games, following 2008's The Hunger Games and 2009's Catching Fire. The book continues the story of Katniss Everdeen, who agrees to unify the districts of Panem in a rebellion against the tyrannical Capitol.",
        rating: 4,
        type: "novel",
        promotion: false
    },
    {
        name: "Mockingjay 2",
        id: 10,
        price: 100,
        quantity: 15,
        image: "https://larasbookclub.files.wordpress.com/2015/11/41k66tfc43l.jpg?w=264&h=373",
        author: "Suzanne Collins",
        detail: "The Hunger Games franchise has finally come to an end with Mockingjay Part 2, which covers roughly the second half of the final book in the trilogy, Mockingjay. And while it's a pretty faithful adaptation of the source material, there are some significant changes to the story. We outlined the five biggest differences between the book and the film (major spoilers for both the book and movie follow, obviously).",
        rating: 4,
        type: "novel",
        promotion: false
    },
    {
        name: "Significance: A Significance Novel - Book 1 (Significance Series)",
        id: 11,
        price: 100,
        quantity: 15,
        image: "https://images-na.ssl-images-amazon.com/images/I/515fPMSPesL._SY346_.jpg",
        author: "Shelly Crane",
        detail: "Maggie is a seventeen year old girl who's had a bad year. Her mom left, her dad is depressed, she's graduating, barely, and her boyfriend of almost three years dumped her for a college football scholarship. Lately she thinks life is all about hanging on by a thread and is gripping tight with everything she has.",
        rating: 3,
        type: "novel",
        promotion: false
    },
    {
        name: "If you're an Aries: Beloved",
        id: 12,
        price: 100,
        quantity: 15,
        image: "https://imgix.bustle.com/uploads/image/2019/10/11/d30b806c-ce43-4348-86e3-8f622304a03a-613vqdxpdwl-1.jpg?w=646&fit=max&auto=format&q=70",
        author: "Toni Morrison",
        detail: "Oh, Aries. If there's one thing you hate, it's losing control of your life. You always want to be in charge, and you think of yourself as a good leader. But what happens when you make a decision that's utterly wrong, and it costs you everything?",
        rating: 3,
        type: "novel",
        promotion: false
    },
    {
        name: "History: The Definitive Visual Guide (From The Dawn of Civilization To The Present Day)",
        id: 13,
        price: 100,
        quantity: 15,
        image: "https://images-na.ssl-images-amazon.com/images/I/51c5umdSXWL._SX414_BO1,204,203,200_.jpg",
        author: "Adam Hart-Davis",
        detail: "Homo sapiens have remained the same species, largely unchanged in genetic makeup and anatomy since the Cro-Magnon era. By contrast, the cultural, social, and technological changes since then have been nothing less than extraordinary. Telling our story, from prehistory to the present day, DK's History is a thought-provoking journey, revealing the common threads and forces that have shaped human history.",
        rating: 4,
        type: "history",
        promotion: false
    },
    {
        name: "Sapiens: A Brief History of Humankind",
        id: 14,
        price: 100,
        quantity: 20,
        image: "https://m.media-amazon.com/images/I/51XyWW6zEXL.jpg",
        author: "Yuval Noah Harari",
        detail: "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution - a number one international best seller - that explores the ways in which biology and history have defined us and enhanced our understanding of what it means to be human.",
        rating: 3,
        type: "history",
        promotion: false
    },
    {
        name: "Timelines of History: The Ultimate Visual Guide to the Events That Shaped the World, 2nd Edition",
        id: 15,
        price: 100,
        quantity: 15,
        image: "https://images-na.ssl-images-amazon.com/images/I/618JMH2EcBL._SX416_BO1,204,203,200_.jpg",
        author: "DK",
        detail: "Beginning with the emergence of our earliest African ancestors and taking readers through the history of cultures and nations around the world to arrive at the present day, Timelines of History caters to readers who want a broad overview, a good story to read, or the nitty-gritty of historical events.",
        rating: 2,
        type: "history",
        promotion: false
    },
    {
        name: "Bad Days in History: A Gleefully Grim Chronicle of Misfortune, Mayhem, and Misery for Every Day of the Year",
        id: 16,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/515gVgCPbtL._SX318_BO1,204,203,200_.jpg",
        author: "Michael Farquhar",
        detail: "National Geographic author Michael Farquhar uncover an instance of bad luck, epic misfortune, and unadulterated mayhem tied to every day of the year. From Caligula's blood-soaked end to hotelier Steve Wynn's unfortunate run-in with a priceless Picasso, these 365 tales of misery include lost fortunes (like the would-be Apple investor who pulled out in 1977 and missed out on a $30 billion-dollar windfall), romance gone wrong (like the 16th-century Shah who experimented with an early form of Viagra with empire-changing results), and truly bizarre moments (like the Great Molasses Flood of 1919).",
        rating: 3,
        type: "history",
        promotion: false
    },
    {
        name: "A Modern History of Japan: From Tokugawa Times to the Present 4th Edition",
        id: 17,
        price: 100,
        quantity: 23,
        image: "https://images-na.ssl-images-amazon.com/images/I/517p-0NK6vL._SX329_BO1,204,203,200_.jpg",
        author: "Andrew Gordon ",
        detail: "A Modern History of Japan: From Tokugawa Times to the Present, Fourth Edition, paints a richly nuanced and strikingly original portrait of the last two centuries of Japanese history. It takes students from the days of the shogunate the feudal overlordship of the Tokugawa family through the modernizing revolution launched by midlevel samurai in the late nineteenth century; the adoption of Western hairstyles, clothing, and military organization; and the nation's first experiments with mass democracy after World War I. Author Andrew Gordon offers the finest synthesis to date of Japan's passage through militarism, World War II, the American occupation, and the subsequent economic rollercoaster.",
        rating: 1,
        type: "history",
        promotion: false
    },
    {
        name: "The Pioneers: The Heroic Story of the Settlers Who Brought the American Ideal West ",
        id: 18,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/51lvyCkmKbL._SX334_BO1,204,203,200_.jpg",
        author: "David McCullough ",
        detail: "Pulitzer Prize–winning historian David McCullough rediscovers an important and dramatic chapter in the American story—the settling of the Northwest Territory by dauntless pioneers who overcame incredible hardships to build a community based on ideals that would come to define our country.",
        rating: 2,
        type: "history",
        promotion: false
    },
    {
        name: "One Piece: East Blue 1-2-3 ",
        id: 19,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/61TC4pdMdDL._SX331_BO1,204,203,200_.jpg",
        author: "DK",
        detail: "With all the Officer Agents defeated, only Crocodile and his final plan to destroy the palace stands in the way of peace. While Luffy battles it out with the evil Croc in the royal tombs, Vivi and the rest of the Straw Hats have to find the bomb before it blows up the capital--with everyone in it!",
        rating: 5,
        type: "manga",
        promotion: false
    },
    {
        name: "One Piece, Vol. 92 (92)",
        id: 20,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/61su5A50q0L._SX331_BO1,204,203,200_.jpg",
        author: "Eiichiro Oda",
        detail: "The Straw Hats are just starting to get their bearings in the mysterious samurai kingdom of Wano when Kaido makes his grand appearance as a flying dragon! Kaido is known as the strongest creature alive, so the smart move would be not to antagonize him. But since when does Luffy do the smart thing?!",
        rating: 5,
        type: "manga",
        promotion: false
    },
    {
        name: "One Piece, Vol. 93 (93)",
        id: 21,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/618vXKoUxkL._SX331_BO1,204,203,200_.jpg",
        author: "Eiichiro Oda",
        detail: "As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber…at the cost of never being able to swim again! Years, later, Luffy sets off in search of the “One Piece,” said to be the greatest treasure in the world",
        rating: 5,
        type: "manga",
        promotion: false
    },
    {
        name: "One Piece, Vol. 1: Romance Dawn",
        id: 22,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/61k-rBYrBwL._SX331_BO1,204,203,200_.jpg",
        author: "Eiichiro Oda",
        detail: "A new shonen sensation in Japan, this series features Monkey D. Luffy, whose main ambition is to become a pirate. Eating the Gum-Gum Fruit gives him strange powers but also invokes the fruit's curse: anybody who consumes it can never learn to swim. Nevertheless, Monkey and his crewmate Roronoa Zoro, master of the three-sword fighting style, sail the Seven Seas of swashbuckling adventure in search of the elusive treasure",
        rating: 5,
        type: "manga",
        promotion: false
    },
    {
        name: "One Piece, Vol. 89 (89)",
        id: 23,
        price: 100,
        quantity: 20,
        image: "https://images-na.ssl-images-amazon.com/images/I/51Pcc9gUKKL._SX331_BO1,204,203,200_.jpg",
        author: "Eiichiro Oda",
        detail: "ig Mom’s hunger pangs have turned her into an unstoppable force of destruction and she has her eyes on the Thousand Sunny. The only thing that has any chance of stopping her is a giant wedding cake Sani is helping construct, but can they get it to her in time? Meanwhile, Luffy's battle against Katakuri heads to a climactic finish!",
        rating: 5,
        type: "manga",
        promotion: false
    }
]